a = int(input('Enter value for a\n'))
b = int(input('Enter value for b\n'))

print('\n')
print('Arithmetic Operators')
print('Sum: ',a+b)
print('Diff: ',a-b)
print('Prod: ',a*b)
print('Quot: ',b/a)
print('Remnder: ',b%a)
print('Floor Divisn: ',b//a)
print('Exponent: ',a**b)

print('\n')
print('Relational Operators')
print('a == b:', a == b)
print('a != b:', a != b)
print('a >= b:', a >= b)
print('a <= b:', a <= b)
print('a > b:', a > b)
print('a < b:', a < b)

print('\n')
print('Logical Operators')
print('a or b:', a or b)
print('a and b:', a and b)

print('\n')
print('Assignment Operators')
print()